(* End-to-end example and e2e test of the bridge.

   The signature below is the source of truth: the PPX expands it into
   functions that call service "spec" over a unix socket, and the wrapper
   server (spec_server.py, generated by `utf gen python`) dispatches to
   spec_functions.py. The first call here spawns that server automatically
   (see bridge/client.ml for the rules).

   Run it with `dune runtest`, or regenerate the python side after changing
   the signature with:

     dune exec utf -- gen python test/test_universal_testing_framework.ml *)

module Spec : sig
  val add : a:int -> b:int -> int
  val greet : s:string -> bool
  val names : n:int -> string list
  val scale : x:float -> y:float -> float
  val echo : s:string -> string
  val pair_sum : int -> int -> int
  val squares : n:int -> int list list
  val explode : x:int -> int
  val wrong_type : x:int -> int
end = struct end [@@utest]

let contains (haystack : string) (needle : string) : bool =
  let needle_length = String.length needle in
  let rec scan index =
    index + needle_length <= String.length haystack
    && (String.sub haystack index needle_length = needle || scan (index + 1))
  in
  needle_length = 0 || scan 0

let expect_bridge_error (fragment : string) (thunk : unit -> 'a) : unit =
  match thunk () with
  | exception Utf_bridge.Error message ->
      Alcotest.(check bool)
        (Printf.sprintf "error %S mentions %S" message fragment)
        true
        (contains message fragment)
  | _ -> Alcotest.failf "expected a bridge error mentioning %S" fragment

let cases =
  [
    Alcotest.test_case "int round trip" `Quick (fun () ->
        Alcotest.(check int) "1 + 2" 3 (Spec.add ~a:1 ~b:2));
    Alcotest.test_case "bool round trip" `Quick (fun () ->
        Alcotest.(check bool) "non-empty" true (Spec.greet ~s:"hi");
        Alcotest.(check bool) "empty" false (Spec.greet ~s:""));
    Alcotest.test_case "list round trip" `Quick (fun () ->
        Alcotest.(check (list string))
          "0..2" [ "0"; "1"; "2" ] (Spec.names ~n:3));
    Alcotest.test_case "float round trip" `Quick (fun () ->
        Alcotest.(check (float 1e-9)) "2.0 * 3.0" 6.0 (Spec.scale ~x:2.0 ~y:3.0));
    Alcotest.test_case "string round trip (utf-8 and escapes)" `Quick (fun () ->
        let value = "héllo \"quoted\"\n\ttabbed — 😀" in
        Alcotest.(check string) "echo" value (Spec.echo ~s:value));
    Alcotest.test_case "positional parameters" `Quick (fun () ->
        Alcotest.(check int) "3 + 4" 7 (Spec.pair_sum 3 4));
    Alcotest.test_case "nested list round trip" `Quick (fun () ->
        Alcotest.(check (list (list int)))
          "squares 3" [ [ 0; 0 ]; [ 1; 1 ]; [ 2; 4 ] ] (Spec.squares ~n:3));
    Alcotest.test_case "remote exception propagates" `Quick (fun () ->
        expect_bridge_error "boom" (fun () -> Spec.explode ~x:1));
    Alcotest.test_case "typed boundary catches a bad return" `Quick (fun () ->
        expect_bridge_error "expected int" (fun () -> Spec.wrong_type ~x:1));
  ]

let () =
  Alcotest.run "universal_testing_framework" [ ("bridge e2e", cases) ]
