(* Emits the two python-side files of a service.

   - [<service>_functions.py] holds the implementation. It is only ever
     written when missing (or when the CLI is forced), so generating code
     never destroys work.
   - [<service>_server.py] is the wrapper server: it listens on a unix
     socket, checks the implementation against the generated signature at
     startup, and dispatches type-checked calls to the functions module.

   The OCaml signature is the source of truth. @@EXPECTED@@ in the server is
   generated from the IR so drift between the two sides fails at startup
   with a readable message instead of a confusing runtime error. *)

let rec type_to_python (ty : Ir.ir_type) : string =
  match ty with
  | Ir.Ty_int -> "int"
  | Ir.Ty_float -> "float"
  | Ir.Ty_string -> "str"
  | Ir.Ty_bool -> "bool"
  | Ir.Ty_list inner -> Printf.sprintf "list[%s]" (type_to_python inner)
  | Ir.Ty_custom name -> name
  | Ir.Ty_illegal -> "object"

let substitute ~marker ~value (source : string) : string =
  let marker_length = String.length marker in
  let buffer = Buffer.create (String.length source) in
  let rec scan index =
    if index >= String.length source then ()
    else if
      index + marker_length <= String.length source
      && String.sub source index marker_length = marker
    then (
      Buffer.add_string buffer value;
      scan (index + marker_length))
    else (
      Buffer.add_char buffer source.[index];
      scan (index + 1))
  in
  scan 0;
  Buffer.contents buffer

(* [{"add": {"params": {"a": "int", "b": "int"}, "returns": "int"}, ...}]
   with the parameter order of the OCaml signature (python dicts keep
   insertion order). *)
let expected_manifest (service : Ir.ir_service) : string =
  let entry (func : Ir.ir_func) =
    let params =
      List.map
        (fun (param : Ir.ir_func_param) ->
          Printf.sprintf "%S: %S" param.name (type_to_python param.ty))
        func.args
      |> String.concat ", "
    in
    Printf.sprintf "%S: {\"params\": {%s}, \"returns\": %S}" func.name params
      (type_to_python func.return_type)
  in
  "{\n" ^ (List.map entry service |> String.concat ",\n") ^ "\n}"

let functions_template =
  {py|"""Bridged functions for service '@@SERVICE@@'.

Generated by `utf gen python`; an existing file is kept unless --force is
passed. Keep the parameter names, order and type annotations exactly as
generated: the wrapper server (@@SERVER_FILE@@) checks every call against
them and refuses to start when the implementation has drifted.
"""


@@DEFINITIONS@@
|py}

let functions_stub ~service_id (service : Ir.ir_service) : string =
  let definitions =
    List.map
      (fun (func : Ir.ir_func) ->
        let parameters =
          List.map
            (fun (param : Ir.ir_func_param) ->
              Printf.sprintf "%s: %s" param.name (type_to_python param.ty))
            func.args
          |> String.concat ", "
        in
        Printf.sprintf "def %s(%s) -> %s:\n    raise NotImplementedError(%S)"
          func.name parameters
          (type_to_python func.return_type)
          func.name)
      service
    |> String.concat "\n\n\n"
  in
  functions_template
  |> substitute ~marker:"@@SERVICE@@" ~value:service_id
  |> substitute ~marker:"@@SERVER_FILE@@" ~value:(Names.server_file service_id)
  |> substitute ~marker:"@@DEFINITIONS@@" ~value:definitions

let server_template =
  {py|#!/usr/bin/env python3
"""UTF wrapper server for service '@@SERVICE@@'.

Generated by `utf gen python`; do not edit. The implementation lives in
'@@FUNCTIONS_MODULE@@.py' next to this file.

Speaks one JSON object per line over a unix domain socket:
  request:  {"service": "...", "func": "...", "args": {"a": 1, ...}}
  response: {"ok": true, "value": <value>}
          | {"ok": false, "error": "..."}
"""
import argparse
import importlib
import inspect
import json
import os
import signal
import socket
import sys
import tempfile
import threading
import time
import traceback
import typing

SERVICE = "@@SERVICE@@"
FUNCTIONS_MODULE = "@@FUNCTIONS_MODULE@@"

# Generated from the OCaml signature: the source of truth for the parameters,
# their order and their types. Checked against the implementation at startup
# and against every incoming request.
EXPECTED = @@EXPECTED@@

DEBUG = os.environ.get("UTF_DEBUG") == "1"
PARENT_POLL_SECONDS = 1.0


def default_socket():
    return os.path.join(tempfile.gettempdir(), "@@DEFAULT_SOCKET_NAME@@")


def log(message):
    if DEBUG:
        print(f"[utf {SERVICE}] {message}", file=sys.stderr, flush=True)


def fail(message):
    print(f"[utf {SERVICE}] error: {message}", file=sys.stderr, flush=True)


def load_functions():
    try:
        return importlib.import_module(FUNCTIONS_MODULE)
    except Exception:
        fail(f"cannot import '{FUNCTIONS_MODULE}':")
        traceback.print_exc()
        sys.exit(2)


def type_name(annotation):
    if annotation is int:
        return "int"
    if annotation is float:
        return "float"
    if annotation is str:
        return "str"
    if annotation is bool:
        return "bool"
    if annotation is typing.Any:
        return "any"
    if typing.get_origin(annotation) is list:
        arguments = typing.get_args(annotation)
        element = type_name(arguments[0]) if arguments else "any"
        return f"list[{element}]"
    return repr(annotation)


def check_signatures(functions):
    """Validate the implementation against the OCaml signature.

    Returns (hints, problems); problems is empty when the implementation
    matches the generated signature exactly."""
    hints = {}
    problems = []
    for name, expected in EXPECTED.items():
        function = getattr(functions, name, None)
        if function is None or not callable(function):
            problems.append(f"missing function: {name}")
            continue
        parameters = inspect.signature(function).parameters
        actual = []
        unsupported = False
        for parameter in parameters.values():
            if parameter.kind is not parameter.POSITIONAL_OR_KEYWORD:
                problems.append(
                    f"{name}: parameter {parameter.name!r} is not a plain "
                    "positional-or-keyword parameter"
                )
                unsupported = True
                continue
            actual.append(parameter.name)
        if unsupported:
            continue
        if actual != list(expected["params"].keys()):
            problems.append(
                f"{name}: parameters {actual} do not match the expected "
                f"{list(expected['params'].keys())}"
            )
            continue
        try:
            resolved = typing.get_type_hints(function)
        except Exception as error:
            problems.append(f"{name}: cannot resolve type annotations: {error}")
            continue
        for parameter_name, expected_type in expected["params"].items():
            if parameter_name not in resolved:
                problems.append(
                    f"{name}: parameter {parameter_name!r} has no type annotation"
                )
            elif type_name(resolved[parameter_name]) != expected_type:
                problems.append(
                    f"{name}: parameter {parameter_name!r} is annotated as "
                    f"{type_name(resolved[parameter_name])}, expected "
                    f"{expected_type}"
                )
        if "return" not in resolved:
            problems.append(f"{name}: no return type annotation")
        elif type_name(resolved["return"]) != expected["returns"]:
            problems.append(
                f"{name}: return is annotated as {type_name(resolved['return'])}, "
                f"expected {expected['returns']}"
            )
        hints[name] = resolved
    return hints, problems


def describe(value):
    return type(value).__name__


def convert(annotation, value, where):
    """Convert one JSON value to the declared python type, or raise TypeError."""
    if annotation is int:
        if isinstance(value, bool) or not isinstance(value, int):
            raise TypeError(f"{where}: expected int, got {describe(value)}")
        return value
    if annotation is float:
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise TypeError(f"{where}: expected float, got {describe(value)}")
        return float(value)
    if annotation is bool:
        if not isinstance(value, bool):
            raise TypeError(f"{where}: expected bool, got {describe(value)}")
        return value
    if annotation is str:
        if not isinstance(value, str):
            raise TypeError(f"{where}: expected str, got {describe(value)}")
        return value
    if annotation is typing.Any:
        return value
    if typing.get_origin(annotation) is list:
        arguments = typing.get_args(annotation)
        element = arguments[0] if arguments else typing.Any
        if not isinstance(value, list):
            raise TypeError(f"{where}: expected list, got {describe(value)}")
        return [
            convert(element, item, f"{where}[{index}]")
            for index, item in enumerate(value)
        ]
    raise TypeError(f"{where}: unsupported type annotation {annotation!r}")


def dispatch(request, functions, hints):
    if not isinstance(request, dict):
        return {"ok": False, "error": "bad request: expected a JSON object"}
    if request.get("service") != SERVICE:
        return {
            "ok": False,
            "error": (
                f"bad request: service {request.get('service')!r} does not "
                f"match {SERVICE!r}"
            ),
        }
    name = request.get("func")
    if not isinstance(name, str) or name not in EXPECTED:
        return {"ok": False, "error": f"bad request: unknown function {name!r}"}
    arguments = request.get("args")
    if not isinstance(arguments, dict):
        return {"ok": False, "error": "bad request: args must be a JSON object"}
    expected = EXPECTED[name]["params"]
    missing = [parameter for parameter in expected if parameter not in arguments]
    unexpected = [key for key in arguments if key not in expected]
    if missing or unexpected:
        return {
            "ok": False,
            "error": (
                f"bad request: {name}: argument mismatch "
                f"(missing={missing}, unexpected={unexpected})"
            ),
        }
    resolved = hints[name]
    try:
        converted = {
            parameter: convert(
                resolved[parameter], arguments[parameter], f"{name}.{parameter}"
            )
            for parameter in expected
        }
        result = getattr(functions, name)(**converted)
        result = convert(resolved["return"], result, f"{name} -> return")
    except Exception as error:
        if DEBUG:
            traceback.print_exc()
        return {
            "ok": False,
            "error": f"remote error: {type(error).__name__}: {error}",
        }
    return {"ok": True, "value": result}


def serve_connection(connection, functions, hints):
    try:
        stream = connection.makefile("rw", encoding="utf-8", newline="\n")
    except OSError:
        connection.close()
        return
    try:
        with stream:
            for line in stream:
                line = line.strip()
                if not line:
                    continue
                try:
                    request = json.loads(line)
                except ValueError as error:
                    response = {
                        "ok": False,
                        "error": f"bad request: invalid JSON: {error}",
                    }
                else:
                    response = dispatch(request, functions, hints)
                stream.write(
                    json.dumps(response, ensure_ascii=False, separators=(",", ":"))
                    + "\n"
                )
                stream.flush()
    except (BrokenPipeError, ConnectionResetError, OSError, ValueError):
        pass
    finally:
        try:
            connection.close()
        except OSError:
            pass


def parent_alive(pid):
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except OSError:
        return True
    return True


def serve(socket_path, parent_pid):
    functions = load_functions()
    hints, problems = check_signatures(functions)
    if problems:
        fail("the implementation does not match the generated signature:")
        for problem in problems:
            fail(f"  - {problem}")
        sys.exit(2)

    if os.path.exists(socket_path):
        os.unlink(socket_path)
    server = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    try:
        server.bind(socket_path)
        server.listen(8)
        server.settimeout(0.5)
        log(f"listening on {socket_path}")

        stopping = threading.Event()

        def stop(signum, frame):
            stopping.set()

        signal.signal(signal.SIGTERM, stop)
        signal.signal(signal.SIGINT, stop)

        last_parent_check = 0.0
        while not stopping.is_set():
            now = time.monotonic()
            if parent_pid is not None and now - last_parent_check >= PARENT_POLL_SECONDS:
                last_parent_check = now
                if not parent_alive(parent_pid):
                    log(f"parent process {parent_pid} is gone; exiting")
                    break
            try:
                connection, _ = server.accept()
            except socket.timeout:
                continue
            thread = threading.Thread(
                target=serve_connection,
                args=(connection, functions, hints),
                daemon=True,
            )
            thread.start()
    finally:
        server.close()
        try:
            os.unlink(socket_path)
        except OSError:
            pass


def main():
    global FUNCTIONS_MODULE
    parser = argparse.ArgumentParser(
        description=f"UTF wrapper server for service '{SERVICE}'"
    )
    parser.add_argument(
        "--socket",
        default=default_socket(),
        help="unix socket path to listen on",
    )
    parser.add_argument(
        "--parent-pid",
        type=int,
        default=None,
        help="exit once this process no longer exists",
    )
    parser.add_argument(
        "--functions",
        default=FUNCTIONS_MODULE,
        help="module to import the implementation from",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="only validate the implementation against the signature, then exit",
    )
    arguments = parser.parse_args()
    FUNCTIONS_MODULE = arguments.functions

    if arguments.check:
        functions = load_functions()
        _, problems = check_signatures(functions)
        if problems:
            for problem in problems:
                fail(f"  - {problem}")
            sys.exit(2)
        print(f"ok: {len(EXPECTED)} functions validated")
        return 0

    serve(arguments.socket, arguments.parent_pid)
    return 0


if __name__ == "__main__":
    sys.exit(main())
|py}

let server_source ~service_id (service : Ir.ir_service) : string =
  server_template
  |> substitute ~marker:"@@SERVICE@@" ~value:service_id
  |> substitute ~marker:"@@FUNCTIONS_MODULE@@"
       ~value:(Names.functions_module service_id)
  |> substitute ~marker:"@@EXPECTED@@" ~value:(expected_manifest service)
  |> substitute ~marker:"@@DEFAULT_SOCKET_NAME@@"
       ~value:("utf_bridge_" ^ service_id ^ ".sock")
